// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechPulse.DAL.Context;

#nullable disable

namespace TechPulse.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531203059_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechPulse.DAL.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "AI",
                            Description = "OpenAI's latest model sets new records in reasoning and coding tasks.",
                            PublishedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "GPT-5 Redefines Language Model Benchmarks"
                        },
                        new
                        {
                            Id = 2,
                            Category = "WebDevelopment",
                            Description = "The new signals-based approach eliminates the need for NgRx in most apps.",
                            PublishedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Angular 19 Signals API Changes State Management"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Security",
                            Description = "Security researchers disclosed a widespread flaw affecting cloud instances.",
                            PublishedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Critical Zero-Day Vulnerability Patched in Cloud Providers"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
